services:
  db:
    image: postgres:15-alpine
    container_name: wellconnect-db
    environment:
      POSTGRES_DB: ${SPRING_DATASOURCE_URL}
      POSTGRES_USER: ${SPRING_DATASOURCE_USERNAME}
      POSTGRES_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - wellconnect-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: wellconnect-backend
    ports:
      - "10000:10000"
    environment:
      - POSTGRES_DB:${SPRING_DATASOURCE_URL}
      - POSTGRES_USER:${SPRING_DATASOURCE_USERNAME}
      - POSTGRES_PASSWORD:${SPRING_DATASOURCE_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRATION=${JWT_EXPIRATION}
      - ENCRYPTION_KEY=${ENCRYPTION_KEY}
      - SERVER_PORT=${SERVER_PORT}
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE:}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - ADMIN_NAME=${ADMIN_NAME}
      - ADMIN_EMAIL=${ADMIN_EMAIL}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
    depends_on:
      - db
    networks:
      - wellconnect-network

  # Remove local Redis since we're using remote Redis
  # redis:
  #   image: redis:7-alpine
  #   container_name: wellconnect-redis
  #   ports:
  #     - "6379:6379"

volumes:
  postgres_data:

networks:
  wellconnect-network:
    driver: bridge
